package com.exam.entity;

// Generated 2015-6-6 10:52:06 by Hibernate Tools 3.2.2.GA


/**
 * Users generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	
	private int cid;
	private String types;//1=agent 0=common customer 3=other
	private int agent_customer_cid;
	private int sex;
	private String customer_name;
	private String phone;
	private String address;
	private String comments;
	
	public int getCid() {
		return cid;
	}
	public void setCid(int cid) {
		this.cid = cid;
	}
	public String getTypes() {
		return types;
	}
	public void setTypes(String types) {
		this.types = types;
	}
	public int getAgent_customer_cid() {
		return agent_customer_cid;
	}
	public void setAgent_customer_cid(int agent_customer_cid) {
		this.agent_customer_cid = agent_customer_cid;
	}
	public int getSex() {
		return sex;
	}
	public void setSex(int sex) {
		this.sex = sex;
	}
	public String getCustomer_name() {
		return customer_name;
	}
	public void setCustomer_name(String customer_name) {
		this.customer_name = customer_name;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
	
	

}
