package com.exam.entity;

// Generated 2015-6-6 10:52:06 by Hibernate Tools 3.2.2.GA


/**
 * Users generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	
	private int pid;
	private String product_name;
	private float volume;
	private float price;
	private float cash_return;//the return cash (in YUAN) for sale one product
	private String comments;
	public int getPid() {
		return pid;
	}
	public void setPid(int pid) {
		this.pid = pid;
	}
	public String getProduct_name() {
		return product_name;
	}
	public void setProduct_name(String product_name) {
		this.product_name = product_name;
	}
	public float getVolume() {
		return volume;
	}
	public void setVolume(float volume) {
		this.volume = volume;
	}
	public float getPrice() {
		return price;
	}
	public void setPrice(float price) {
		this.price = price;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	public float getCash_return() {
		return cash_return;
	}
	public void setCash_return(float cash_return) {
		this.cash_return = cash_return;
	}
	

	
	
	

}
