package com.exam.entity;


// Generated 2015-6-6 10:52:06 by Hibernate Tools 3.2.2.GA


/**
 * Users generated by hbm2java
 */
public class SalesHistory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	
	private int sid;
	private int customer_id;
	private int product_id;
	private int quantity;
	private String sale_time;
	private String comments;
	public int getSid() {
		return sid;
	}
	public void setSid(int sid) {
		this.sid = sid;
	}
	public int getCustomer_id() {
		return customer_id;
	}
	public void setCustomer_id(int customer_id) {
		this.customer_id = customer_id;
	}
	public int getProduct_id() {
		return product_id;
	}
	public void setProduct_id(int product_id) {
		this.product_id = product_id;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public String getSale_time() {
		return sale_time;
	}
	public void setSale_time(String sale_time) {
		this.sale_time = sale_time;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
	

}
