package com.exam.entity;

// Generated 2015-6-6 10:52:06 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.servlet.http.HttpSessionBindingEvent;
import javax.servlet.http.HttpSessionBindingListener;

import com.framework.auto.anno.IDMarker;
import com.framework.auto.anno.ShowMarker;
import com.framework.auto.anno.ZnValue;
import com.framework.auto.util.OnLines;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable, HttpSessionBindingListener {

	private static final long serialVersionUID = 1L;

	
	@IDMarker(true)
	private int userid;
	
	@ShowMarker(true)
	@ZnValue("用户名")
	private String username;

	@ShowMarker(true)
	@ZnValue("用户密码")
	private String password;
	
	@ShowMarker(true)
	@ZnValue("性别")
	private String sex;
	
	@ShowMarker(true)
	@ZnValue("邮箱")
	private String email;
	
	@ShowMarker(true)
	@ZnValue("用户住址")
	private String address;

	@ShowMarker(true)
	@ZnValue("手机")
	private String cellphone;
	
	
	@ShowMarker(true)
	@ZnValue("出生日期")
	private Date birthday;
	
	@ShowMarker(true)
	@ZnValue("备注")
	private String comments;

	private int roleid;
	
	

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public int getRoleid() {
		return roleid;
	}

	public void setRoleid(int roleid) {
		this.roleid = roleid;
	}


	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Override
	public void valueBound(HttpSessionBindingEvent arg0) {
		
		System.out.println(this.getClass().getName()+" valueBound");
		
	}

	@Override
	public void valueUnbound(HttpSessionBindingEvent arg0) {
		
		System.out.println(this.getClass().getName()+" valueBound");
	}
	
	
	

}
