package com.framework.auto.basicentity;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import com.framework.auto.anno.IDMarker;
import com.framework.auto.anno.LargeObjMarker;
import com.framework.auto.anno.ShowMarker;
import com.framework.auto.anno.ZnValue;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@IDMarker(true)
	private int gid;
	
	@ShowMarker(true)
	@ZnValue("用户组名")
	private String gname;
	
	@ShowMarker(true)
	@ZnValue("用户组描述")
	private String gdescription;
	
	@LargeObjMarker(true)
	private Set<UgRelation> ugRelations = new HashSet<UgRelation>(0);
	
	@LargeObjMarker(true)
	private Set<GrRelation> grRelations = new HashSet<GrRelation>(0);

	public Groups() {
	}

	public Groups(int gid) {
		this.gid = gid;
	}

	public Groups(int gid, String gname, String gdescription,
			Set<UgRelation> ugRelations, Set<GrRelation> grRelations) {
		this.gid = gid;
		this.gname = gname;
		this.gdescription = gdescription;
		this.ugRelations = ugRelations;
		this.grRelations = grRelations;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public String getGname() {
		return this.gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public String getGdescription() {
		return this.gdescription;
	}

	public void setGdescription(String gdescription) {
		this.gdescription = gdescription;
	}

	public Set<UgRelation> getUgRelations() {
		return this.ugRelations;
	}

	public void setUgRelations(Set<UgRelation> ugRelations) {
		this.ugRelations = ugRelations;
	}

	public Set<GrRelation> getGrRelations() {
		return this.grRelations;
	}

	public void setGrRelations(Set<GrRelation> grRelations) {
		this.grRelations = grRelations;
	}

}
