package com.framework.auto.basicentity;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

/**
 * GrRelation generated by hbm2java
 */
public class GrRelation implements java.io.Serializable {

	private int grid;
	private Groups groups;
	private Roles roles;

	public GrRelation() {
	}

	public GrRelation(int grid, Groups groups, Roles roles) {
		this.grid = grid;
		this.groups = groups;
		this.roles = roles;
	}

	public int getGrid() {
		return this.grid;
	}

	public void setGrid(int grid) {
		this.grid = grid;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
