package com.framework.auto.basicentity;

import com.framework.auto.anno.IDMarker;
import com.framework.auto.anno.ShowMarker;
import com.framework.auto.anno.ZnValue;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

/**
 * Operations generated by hbm2java
 */
public class Operations implements java.io.Serializable {

	@IDMarker(true)
	private int optid;
	
	@ShowMarker(true)
	@ZnValue("角色名称")
	private Roles roles;
	
	@ShowMarker(true)
	@ZnValue("操作名称")
	private String optname;

	public Operations() {
	}

	public Operations(int optid) {
		this.optid = optid;
	}

	public Operations(int optid, Roles roles, String optname) {
		this.optid = optid;
		this.roles = roles;
		this.optname = optname;
	}

	public int getOptid() {
		return this.optid;
	}

	public void setOptid(int optid) {
		this.optid = optid;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getOptname() {
		return this.optname;
	}

	public void setOptname(String optname) {
		this.optname = optname;
	}

}
