package com.framework.auto.basicentity;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.framework.auto.anno.IDMarker;
import com.framework.auto.anno.LargeObjMarker;
import com.framework.auto.anno.ShowMarker;
import com.framework.auto.anno.ZnValue;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@IDMarker(true)
	private int rid;
	
	@ShowMarker(true)
	@ZnValue("角色名称")
	private String rname;
	
	@ShowMarker(true)
	@ZnValue("角色描述")
	private String rdescription;
	
	@ShowMarker(true)
	@ZnValue("操作时间")
	private Date optdate;
	
	@ShowMarker(true)
	@ZnValue("备注")
	private String comments;
	
	@LargeObjMarker(true)
	private Set<Operations> operationses = new HashSet<Operations>(0);
	
	@LargeObjMarker(true)
	private Set<UrRelation> urRelations = new HashSet<UrRelation>(0);
	
	@LargeObjMarker(true)
	private Set<GrRelation> grRelations = new HashSet<GrRelation>(0);

	public Roles() {
	}

	public Roles(int rid, String rname) {
		this.rid = rid;
		this.rname = rname;
	}

	public Roles(int rid, String rname, String rdescription, Date optdate,
			String comments, Set<UrRelation> urRelations,
			Set<Operations> operationses, Set<GrRelation> grRelations) {
		this.rid = rid;
		this.rname = rname;
		this.rdescription = rdescription;
		this.optdate = optdate;
		this.comments = comments;
		this.urRelations = urRelations;
		this.operationses = operationses;
		this.grRelations = grRelations;
	}

	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public String getRdescription() {
		return this.rdescription;
	}

	public void setRdescription(String rdescription) {
		this.rdescription = rdescription;
	}

	public Date getOptdate() {
		return this.optdate;
	}

	public void setOptdate(Date optdate) {
		this.optdate = optdate;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set<UrRelation> getUrRelations() {
		return this.urRelations;
	}

	public void setUrRelations(Set<UrRelation> urRelations) {
		this.urRelations = urRelations;
	}

	public Set<Operations> getOperationses() {
		return this.operationses;
	}

	public void setOperationses(Set<Operations> operationses) {
		this.operationses = operationses;
	}

	public Set<GrRelation> getGrRelations() {
		return this.grRelations;
	}

	public void setGrRelations(Set<GrRelation> grRelations) {
		this.grRelations = grRelations;
	}

}
