package com.framework.auto.basicentity;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

/**
 * UgRelation generated by hbm2java
 */
public class UgRelation implements java.io.Serializable {

	private int ugid;
	private Groups groups;
	private Users users;

	public UgRelation() {
	}

	public UgRelation(int ugid, Groups groups, Users users) {
		this.ugid = ugid;
		this.groups = groups;
		this.users = users;
	}

	public int getUgid() {
		return this.ugid;
	}

	public void setUgid(int ugid) {
		this.ugid = ugid;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
