package com.framework.auto.basicentity;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

/**
 * UrRelation generated by hbm2java
 */
public class UrRelation implements java.io.Serializable {

	private int urid;
	private Users users;
	private Roles roles;

	public UrRelation() {
	}

	public UrRelation(int urid, Users users, Roles roles) {
		this.urid = urid;
		this.users = users;
		this.roles = roles;
	}

	public int getUrid() {
		return this.urid;
	}

	public void setUrid(int urid) {
		this.urid = urid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
