package com.framework.auto.basicentity;

// Generated 2010-6-1 15:25:49 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.framework.auto.anno.IDMarker;
import com.framework.auto.anno.LargeObjMarker;
import com.framework.auto.anno.ShowMarker;
import com.framework.auto.anno.ZnValue;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@IDMarker(true)
	private int uid;
	
	@ShowMarker(true)
	@ZnValue("用户名")
	private String username;
	
	@ShowMarker(true)
	@ZnValue("真实姓名")
	private String realname;
	
	@ShowMarker(true)
	@ZnValue("用户密码")
	private String password;
	
	@ShowMarker(true)
	@ZnValue("性别")
	private String sex;
	
	@ShowMarker(true)
	@ZnValue("邮箱")
	private String email;
	
	@ShowMarker(true)
	@ZnValue("用户住址")
	private String address;
	
	@ShowMarker(true)
	@ZnValue("出生日期")
	private Date birthday;
	
	
	@ShowMarker(true)
	@ZnValue("备注")
	private String comments;
	
	@LargeObjMarker(true)
	private Set<UgRelation> ugRelations = new HashSet<UgRelation>(0);
	
	@LargeObjMarker(true)
	private Set<UrRelation> urRelations = new HashSet<UrRelation>(0);

	public Users() {
	}

	public Users(int uid, String username) {
		this.uid = uid;
		this.username = username;
	}

	public Users(int uid, String username, String realname, String password,
			String sex, String email, String address, Date birthday,
			Date optdate, String comments, Set<UgRelation> ugRelations,
			Set<UrRelation> urRelations) {
		this.uid = uid;
		this.username = username;
		this.realname = realname;
		this.password = password;
		this.sex = sex;
		this.email = email;
		this.address = address;
		this.birthday = birthday;
		this.comments = comments;
		this.ugRelations = ugRelations;
		this.urRelations = urRelations;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}


	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set<UgRelation> getUgRelations() {
		return this.ugRelations;
	}

	public void setUgRelations(Set<UgRelation> ugRelations) {
		this.ugRelations = ugRelations;
	}

	public Set<UrRelation> getUrRelations() {
		return this.urRelations;
	}

	public void setUrRelations(Set<UrRelation> urRelations) {
		this.urRelations = urRelations;
	}

}
